### ISSUE TITLE
이슈 탭을 열어놓은 것은 조동아리 주도 개발 지침 위반입니닷

### ISSUE THREAD

**Issue by fixalot84** [Lee-WonJun/JDD-Description#21]
> 방어적 프로그래밍을 해라 코드로 방어하지 말고 너에게 들어오는 일감을 방어해라

이 항목에 따라 이슈 탭은 열지 않는 것이 좋을 것 같습니다.

🤣🤣🤣🤣

**Comment by Lee-WonJun** [comment]
LGTM
